# Matrix Factorization sweep configuration

program: scripts/train.py
method: random
metric:
  goal: minimize
  name: val_rmse

parameters:
  model_type:
    value: mf
  trainer_type:
    value: base
  scenario:
    value: warm
  
  # Hyperparameters to sweep
  batch_size:
    values: [8000, 16384]
  epochs:
    value: 20
  learning_rate:
    distribution: uniform
    min: 0.001
    max: 0.01
  emb_dim:
    values: [8, 16, 32]
  weight_decay:
    values: [0.00001, 0.00005, 0.0001, 0.0005]
  biases:
    values: [
      "user,item",
      "user,item,category,store"
    ]