# Neural Collaborative Filtering cold-start configuration

# Model parameters
model_type: ncf
trainer_type: ncf
scenario: cold_start

# Hyperparameters
emb_dim: 16
batch_size: 1024
learning_rate: 0.0005
weight_decay: 0.1
epochs: 1
image_model: fashion_clip
test_ratio: 0.2