program: MF/run_sweep.py
command:
  - /usr/bin/python3 # change this to the path of venv
  - ${program}
method: random
metric:
  goal: minimize
  name: val_loss
parameters:
  batch_size:
    values: [8000,16384]
  epochs:
    value: 20
  learning_rate:
    distribution: uniform
    min: 0.001
    max: 0.01
  emb_dim:
    values: [ 8, 16, 32]
  weight_decay:
    values: [0.00001, 0.00005, 0.0001, 0.0005]
  biases:
    values: [
#      [],
#      ['user'],
#      ['item'],
#      ['category'],
#      ['store'],
      ['user', 'item'],
#      ['user', 'category'],
#      ['user', 'store'],
#      ['item', 'category'],
#      ['item', 'store'],
#      ['category', 'store'],
#      ['user', 'item', 'category'],
#      ['user', 'item', 'store'],
#      ['user', 'category', 'store'],
#      ['item', 'category', 'store'],
      ['user', 'item', 'category', 'store']
    ]





