# Neural Collaborative Filtering model configuration

# Model parameters
model_type: ncf
trainer_type: base
scenario: warm

# Hyperparameters
emb_dim: 64
batch_size: 8192 #8192
learning_rate: 0.001
weight_decay: 0.00001 #1e-5
epochs: 4
dropout_rate: 0